version: '2'
services:
  php:
    build: build/php
    expose:
      - '9000'
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/symfony:cached
      - ./logs:/var/log
  web:
    build: build/nginx
    restart: always
    ports:
        - '81:80'
    depends_on:
        - php
        - db
    volumes:
        - ./:/var/www/html/symfony:cached
        - ./logs:/var/log/nginx
  db:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_DATABASE=symfony_db
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=127.0.0.1
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql